model_name_or_path: ./Qwen3-4B-Base
adapter_name_or_path: ./saves/qwen3-4b-base/lora/dpo/checkpoint-1875
trust_remote_code: true
stage: sft
finetuning_type: lora
template: qwen3
eval_dataset: tulu3_sft_personas
dataset_dir: ./data
cutoff_len: 2048
max_samples: 100
do_eval: true
do_predict: true
per_device_eval_batch_size: 1
predict_with_generate: true
overwrite_cache: true
max_new_tokens: 512
temperature: 0.7
top_p: 0.9
do_sample: true
output_dir: ./evaluation_results_dpo
report_to: none
do_train: false
