adapter_name_or_path: ./saves/qwen3-4b-base/lora/sft/checkpoint-2532
cutoff_len: 2048
dataset_dir: ./data
do_eval: true
do_predict: true
do_sample: true
do_train: false
eval_dataset: tulu3_sft_personas
finetuning_type: lora
max_new_tokens: 512
max_samples: 100
model_name_or_path: ./Qwen3-4B-Base
output_dir: ./evaluation_results_sft_checkpoint-2532
overwrite_cache: true
per_device_eval_batch_size: 1
predict_with_generate: true
report_to: none
stage: sft
temperature: 0.7
template: qwen3
top_p: 0.9
trust_remote_code: true
